* obs-websocket-el

[2025-05-20 Tue] Announcement: cmack is the new maintainer. Yay! =) - Sacha

Totally bubblegum-and-string at the moment.

You'll need [[https://obsproject.com/][Open Broadcaster Software]] and the [[https://obsproject.com/forum/resources/obs-websocket-remote-control-obs-studio-from-websockets.466/][obs-websocket]] plugin for
it. Set it up in =Tools > WebSockets Server Settings=. Set a password
there.

You will also need [[https://elpa.gnu.org/packages/websocket.html][websocket]], which is available from GNU ELPA. You can install it with
=M-x package-install RET websocket RET=.

You will probably be able to use =M-x obs-websocket-connect= to
connect to your OBS server. I have no idea if it will work for anyone
but me, though. Good luck!

You can use =(setq obs-websocket-password "yourpasswordhere")=
in your Emacs configuration file so that it won't prompt you for the password.

Here is a sample configuration using =use-package= and =transient= features standard in Emacs 30:

#+begin_src emacs-lisp
(use-package websocket
  :ensure t)

(use-package obs-websocket
  :ensure t
  :vc (:url "https://github.com/obs-websocket-el/obs-websocket-el.git"
            :rev :newest)
  :bind (("<f8>" . my/obs-websocket-tmenu))
  :config
  (require 'transient)
  (transient-define-prefix my/obs-websocket-tmenu ()
    "Transient menu for controlling OBS via websocket"
    :refresh-suffixes t
    ["Connection"
     ("c" obs-websocket-connect
      :description "Connect to OBS"
      :transient t
      :inapt-if obs-websocket-connected-p)
     ("Q" "Disconnect" obs-websocket-disconnect)]
    ["Streaming"
     :if obs-websocket-connected-p
     ("sb" "Stream - begin"
      (lambda () (interactive)
        (obs-websocket-send "StartStream")))
     ("se" "Stream - end"
      (lambda () (interactive)
        (obs-websocket-send "StopStream")))]
    ["Scenes"
     :if obs-websocket-connected-p
     ("d" "Desktop"
      (lambda () (interactive)
        (obs-websocket-send "SetCurrentProgramScene" :sceneName "Desktop")))
     ("e" "Emacs"
      (lambda () (interactive)
        (obs-websocket-send "SetCurrentProgramScene" :sceneName "Emacs")))
     ("i" "Intermission"
      (lambda () (interactive)
        (obs-websocket-send "SetCurrentProgramScene" :sceneName "Intermission")))
     ("v" "Browse Channel"
      (lambda () (interactive)
        (browse-url "https://twitch.tv/<your-channel-here>")))
     ("P" "Preview current scene"
      (lambda () (interactive)
        (obs-websocket-send "GetSourceScreenshot"
                            :sourceName obs-websocket-scene
                            :imageFormat "jpeg"
                            :imageHeight 150
                            :callback #'obs-websocket-display-screenshot)))
     ]))
#+end_src


Better installation instructions will eventually be written by
someone, if anyone wants to actually maintain this.

Protocol reference: [[https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md][5.x.x Websocket Protocol Reference]]


Contributors:
- cmack
- sachac: My e-mail address is [[sacha@sachachua.com]], although I tend to reply slowly.
